//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TapHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public int MACTHD { get; set; }
        public int SOHD { get; set; }
        public string MASP { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public Nullable<decimal> THUE { get; set; }
        public Nullable<decimal> GIAMGIA { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
