//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TapHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public int SOHD { get; set; }
        public System.DateTime NGHD { get; set; }
        public string MANV { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<int> TONGSL { get; set; }
        public Nullable<decimal> TONGGIAMGIA { get; set; }
        public Nullable<decimal> TONGTHUE { get; set; }
        public Nullable<decimal> PHAITRA { get; set; }
        public Nullable<decimal> TIENTRALAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
