//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TapHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public string MADVT { get; set; }
        public Nullable<decimal> GIAHIENHANH { get; set; }
        public Nullable<decimal> GIAMOI { get; set; }
        public Nullable<decimal> THUE { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<decimal> GIAMGIA { get; set; }
        public Nullable<int> SOLUONGDABAN { get; set; }
        public string HINHANH { get; set; }
        public string MALOAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual DVT DVT { get; set; }
        public virtual LOAIHANG LOAIHANG { get; set; }
    }
}
